apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlink-config
  namespace: streamlink
data:
  POSTGRES_DB: videochat
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/videochat
  APP_CORS_ALLOWED_ORIGINS: http://streamlink.local,http://localhost:4201,http://127.0.0.1:4201
  LIVEKIT_URL: wss://replace-with-your-livekit-host
